---
- name: Install Mysql package
  yum: name=mysql-server state=present

- name: Create Mysql configuration file
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
